import { Fish } from './fish.component';
import { Injectable } from '@angular/core';

@Injectable()
export class FishService {
    visibleImages = [];

    getFish(id:  number): Fish {
        return FISHES.slice(0).find(fish => fish.id == id);
    }
}
const FISHES=[
{'id' : 1, 'url' : '114177', 'name' : 'Tenca', 'description' : 'A tenca (<i>Tinca tinca</i>) é utilizada na aquacultura, sendo atualmente ocasional e muito rara. A sua introdução é provavelmente muito antiga.', 'data_de_chegada' : '< 1800', 'origem' : 'Europa', 'usos' : 'Pesca desportiva e aquacultura', 'impactos_conhecidos' : 'Não se conhecem'},
{'id' : 2, 'url' : '112581', 'name' : 'Silurno', 'description' : 'O siluro (<i>Silurus glanis</i>) surge em Portugal a partir de populações espanholas do Tejo. É muito apreciada na pesca desportiva.', 'data_de_chegada' : '2006', 'origem' : 'Europa', 'usos' : 'Pesca desportiva.', 'impactos_conhecidos' : 'É um predador que se alimenta principalmente de peixes, lagostins e aves. Em alguns locais preda alguns peixes importantes como a enguia, lampreia e o Sável.'},
{'id' : 3, 'url' : '69989', 'name' : 'Gardon', 'description' : 'O gardon (<i>Rutilus rutilus</i>) foi introduzido inicialmente no rio Ave ocorrendo, principalmente, em vários rios do norte (<i>Cávado e Douro</i>).', 'data_de_chegada' : '2007', 'origem' : 'Europa', 'usos' : 'Pesca desportiva.', 'impactos_conhecidos' : 'O gardon alimenta-se  de zooplanctôn, essencial para a filtração das algas, podendo levar à perda da qualidade da água das barragens.'},
{'id' : 4, 'url' : '91026', 'name' : 'Piscardo', 'description' : 'O piscardo (<i>Phoxinus sp.) foi recentemente detetado num tributário do Douro. Ainda não foi possível determinar que espécie ocorre em Portugal.', 'data_de_chegada' : '2016', 'origem' : 'Penísula Ibérica', 'usos' : 'Desconhece-se a sua utilidade.', 'impactos_conhecidos' : 'Não são conhecidos os seus impactos.'},
{'id' : 5, 'url' : '109062', 'name' : 'Perca-europeia', 'description' : 'A perca-europeia (<i>Perca fluviatilis</i>) ocorre numa pequena área da Beira Baixa, sendo provável a sua expansão para o rio Tejo.', 'data_de_chegada' : '2013', 'origem' : 'Europa', 'usos' : 'Pesca desportiva.', 'impactos_conhecidos' : 'Espécie que preda o zooplâncton, podendo levar à perda da qualidade da água das barragens. Os individuos de maiores dimensões são predadores.'},
{'id' : 6, 'url' : '48156', 'name' : 'Lucioperca', 'description' : 'O lucioperca (<i>Sander lucioperca</i>) surgiu no rio Ave e foi depois introduzido em várias barragens do país para pesca desportiva.', 'data_de_chegada' : '1997', 'origem' : 'Europa', 'usos' : 'Pesca desportiva, interesse gastronómico.', 'impactos_conhecidos' : 'Espécie predadora que se alimenta principalmente de peixes e lagostins. Podendo causar algum impacto nas populações de peixes nas barragens e rios principais.'},
{'id' : 7, 'url' : '55387', 'name' : 'Lúcio', 'description' : 'O lúcio (Esox lucius</i>) é procurado para a pesca desportiva. Este predador ocorre em barragens do norte e em alguns rios principais de Portugal.', 'data_de_chegada' : '1950', 'origem' : 'Europa', 'usos' : 'Pesca desportiva, interesse gastronómico.', 'impactos_conhecidos' : 'Impactos conhecidos: Em rios este peixe preda algumas espécies nativas, como é o caso da boga-de-boca-recta, escalo e o ruivaco. É um predador muito voraz.'},
{'id' : 8, 'url' : '81554', 'name' : 'Peixe-gato-americano / Bagre', 'description' : 'O peixe-gato-americano (<i>Ictalurus punctatus) surgiu no Alqueva a partir de populações espanholas. É procurado pela pesca e usado na aquacultura.', 'data_de_chegada' : '2012', 'origem' : 'América do Norte', 'usos' : 'Pesca desportiva, aquacultura.', 'impactos_conhecidos' : 'São pouco conhecidos os impactos desta espécie, porém sabe-se que os individuos de maiores dimensões são predadores de peixes.'},
{'id' : 9, 'url' : '56899', 'name' : 'Chanchito', 'description' : 'O chanchito (<i>Australoheros facetus</i>) é uma espécie ornamental que ocorre nos rios do sul de Portugal. É territorial e agressiva.', 'data_de_chegada' : '1940', 'origem' : 'América do Sul', 'usos' : 'Ornamental', 'impactos_conhecidos' : 'Peixe muito agressivo, competindo pelo espaço e alimento, sendo claramente melhor competidora que muitas outras espécies.'},
{'id' : 10, 'url' : '58642', 'name' : 'Fundulo', 'description' : 'O fundulo (<i>Fundulus heteroclitus</i>) ocorre em zonas estuarinas do Guadiana e Ria Formosa. Julga-se que chegou a Portugal acidentalmente.', 'data_de_chegada' : '1975', 'origem' : 'América do Norte', 'usos' : 'Ornamental', 'impactos_conhecidos' : 'Impactos conhecidos: É um peixe muito agressivo para com os outros peixes, competindo por espaço e alimento com as outras espécies.'},
{'id' : 11, 'url' : '58612', 'name' : 'Pimpão', 'description' : 'O pimpão (<i>Carassius auratus</i>) terá sido transportado por navegadores Portugueses. É comum em barragens e ocasional em rios.', 'data_de_chegada' : '< 1800', 'origem' : 'Ásia', 'usos' : 'Pesca desportiva', 'impactos_conhecidos' : 'Não se conhecem'},
{'id' : 12, 'url' : '82278', 'name' : 'Peixe-gato-negro', 'description' : 'O peixe-gato-negro (<i>Ameirus melas</i>) surgiu nos rios internacionais. É abundante em barragens e águas paradas', 'data_de_chegada' : '1999', 'origem' : 'América do Norte', 'usos' : 'Pesca desportiva', 'impactos_conhecidos' : 'Perda da qualidade de água em barragens, através da sua alimentação junto ao fundos aumentando a turbidez da água'},
{'id' : 13, 'url' : '424997', 'name' : 'Pimpão-cinzento', 'description' : 'O pimpão-cinzento (<i>Carassius gibelio</i>) é abundante localmente nos principais rios e barragens, sendo as suas populações constituídas apenas por fêmeas.', 'data_de_chegada' : '2012', 'origem' : 'Europa', 'usos' : 'Pesca desportiva.', 'impactos_conhecidos' : 'Atinge grandes densidades populacionais, levando à diminuição da abundância de outras espécies. É responsável pela perda da qualidade de água das barragens.'},
{'id' : 14, 'url' : '53911', 'name' : 'Carpa', 'description' : 'A carpa (<i>Cyprinus carpio</i>) é procurada para a pesca desportiva e utilizada em aquacultura, sendo comum em barragens e ocasional em rios.', 'data_de_chegada' : '< 1800', 'origem' : 'Europa', 'usos' : 'Pesca desportiva, aquacultura, interesse gastronómico.', 'impactos_conhecidos' : 'Perda da qualidade de água em barragens, através do arranque de plantasaquáticas  e aumento da turbidez da água'},
{'id' : 15, 'url' : '53911', 'name' : 'Gambúsia', 'description' : 'A gambúsia (<i>Gambusia holbrooki</i>) foi introduzida em Portugal para combater a malária. É extremamente abundante em águas paradas dos rios do sul.', 'data_de_chegada' : '1932', 'origem' : 'América do Norte', 'usos' : 'Sem utilidade conhecida.', 'impactos_conhecidos' : 'Extremamente agressiva para com os outros peixes, preda os ovos de outras espécies. Compete por espaço e alimento com as outras espécies.'},
{'id' : 16, 'url' : '101591', 'name' : 'Góbio', 'description' : 'O góbio (<i>Gobio lozanoi</i>), nativo do País Basco, foi introduzido como isco vivo para a pesca à truta. É muito abundante em rios.', 'data_de_chegada' : '1921', 'origem' : 'Península Ibérica', 'usos' : 'Sem utilidade conhecida', 'impactos_conhecidos' : 'Não se conhecem'},
{'id' : 17, 'url' : '49614', 'name' : 'Perca-sol', 'description' : 'A perca-sol (<i>Lepomis gibbosus</i>) chegou a Portugal a partir de populações espanholas, sendo amplamente utilizada e dispersa na pesca desportiva.', 'data_de_chegada' : '1978', 'origem' : 'América do Norte', 'usos' : 'Ornamental, pesca desportiva.', 'impactos_conhecidos' : 'Impactos conhecidos: Peixe muito agressivo, competindo pelo espaço e alimento, sendo claramente melhor competidora que muitas outras espécies.'},
{'id' : 18, 'url' : '49587', 'name' : 'Achigã', 'description' : 'O achigã (<i>Micropterus salmoides</i>) foi introduzido oficialmente para desenvolver a pesca desportiva no sul do país. É comum em barragens.', 'data_de_chegada' : '1953', 'origem' : 'América do Norte', 'usos' : 'Pesca desportiva, interesse gastronómico.', 'impactos_conhecidos' : 'Espécie predadora que se alimenta principalmente de lagostins e peixes. Sendo ocasional e pouco abundante nos rios.'},
{'id' : 19, 'url' : '47516', 'name' : 'Truta-arco-íris', 'description' : 'A truta-arco-íris (<i>Oncorhynchus mykiss</i>) foi introduzida oficialmente para a pesca. Ocorre em barragens de montanha e é utilizada em aquacultura.', 'data_de_chegada' : '1898', 'origem' : '', 'usos' : 'Aquacultura e pesca desportiva, interesse gastronómico.', 'impactos_conhecidos' : ' Não se conhecem'},
{'id' : 20, 'url' : '93611', 'name' : 'Alburno', 'description' : 'O alburno (<i>Alburnus alburnus</i>) em menos de 10 anos invadiu o país quase todo (de sul para norte</i>). É muito abundante em barragens e rios.', 'data_de_chegada' : '2000', 'origem' : 'Europa', 'usos' : 'Pesca desportiva.', 'impactos_conhecidos' : 'Perda da qualidade de água em barragens, uma vez que se alimenta de zooplanctôn, essencial para a filtração das algas. Hibrida com as espécies de peixes, o Escalo e o Bordalo.'}
];